use crate::verdict::Ecosystem;

const PYPI_TOP: &[&str] = &[
    "boto3",
    "urllib3",
    "requests",
    "setuptools",
    "certifi",
    "idna",
    "charset-normalizer",
    "typing-extensions",
    "six",
    "python-dateutil",
    "wheel",
    "pyyaml",
    "cryptography",
    "click",
    "numpy",
    "pandas",
    "fastapi",
    "starlette",
    "pydantic",
    "httpx",
    "aiohttp",
    "django",
    "flask",
    "sqlalchemy",
    "rich",
    "tqdm",
    "pillow",
    "matplotlib",
    "scipy",
    "scikit-learn",
    "torch",
    "transformers",
    "huggingface-hub",
    "huggingface_hub",
    "openai",
    "anthropic",
    "langchain",
    "tiktoken",
    "ollama",
    "uvicorn",
    "gunicorn",
    "pytest",
    "ruff",
    "mypy",
    "black",
    "uv",
    "poetry",
    "pip",
];

const NPM_TOP: &[&str] = &[
    "lodash",
    "react",
    "react-dom",
    "next",
    "express",
    "axios",
    "typescript",
    "vue",
    "vite",
    "webpack",
    "eslint",
    "prettier",
    "jest",
    "vitest",
    "tailwindcss",
    "zod",
    "openai",
    "anthropic",
    "langchain",
    "@anthropic-ai/sdk",
    "@types/node",
    "ws",
    "chalk",
    "yargs",
    "commander",
];

pub fn top_packages(ecosystem: Ecosystem) -> &'static [&'static str] {
    match ecosystem {
        Ecosystem::Pypi => PYPI_TOP,
        Ecosystem::Npm => NPM_TOP,
        _ => &[],
    }
}
